import { Exam, Question } from '../types';

export const INITIAL_SEED_EXAMS: Exam[] = [
  {
    id: 'EX-BANGLA-001',
    title: 'বাংলা ভাষা ও ব্যাকরণ — বিপরীতার্থক শব্দ',
    badge: 'ফ্রি পরীক্ষা',
    badge_type: 'free',
    subject: 'বাংলা ভাষা ও ব্যাকরণ',
    topic: 'শব্দ ও পদ',
    post: 'বিসিএস ক্যাডার (BCS)',
    description: 'বাংলা ব্যাকরণের বিপরীতার্থক শব্দ বিষয়ক গুরুত্বপুর্ণ MCQ প্রশ্নাবলী।',
    question_count: 5,
    time_minutes: 5,
    total_marks: 5,
    negative_marks: 0.25,
    marks_per_question: 1,
    has_negative_marking: true,
    pass_mark: 3,
    status: 'active',
    category: 'ফ্রি ট্রায়াল টেস্ট (Free Test)',
    exam_type: 'free',
    exam_format: 'MCQ (বহুনির্বাচনি)',
    created_at: new Date().toISOString(),
    questions: [
      {
        id: 'Q-BNG-LNG-01-04-00001',
        question: '‘সৌম্য’ শব্দের বিপরীতার্থক শব্দ কোনটি?',
        option_a: 'উগ্র',
        option_b: 'শান্ত',
        option_c: 'নম্র',
        option_d: 'গম্ভীর',
        correct_answer: 'option_a',
        explanation: '‘সৌম্য’ অর্থ শান্ত বা প্রশান্ত। এর বিপরীত শব্দ ‘উগ্র’ (ক্রুদ্ধ বা রুক্ষ)।',
        status: 'published',
        subject: 'বাংলা ভাষা ও ব্যাকরণ',
        topic: 'শব্দ ও পদ',
        subtopic: 'বিপরীতার্থক শব্দ',
        code: 'BNG-LNG-01-04',
      },
      {
        id: 'Q-BNG-LNG-01-04-00002',
        question: '‘অনুরাগ’ শব্দের বিপরীত শব্দ কোনটি?',
        option_a: 'বিরাগ',
        option_b: 'রাগ',
        option_c: 'প্রীতি',
        option_d: 'আসক্তি',
        correct_answer: 'option_a',
        explanation: '‘অনুরাগ’ শব্দের বিপরীত শব্দ হলো ‘বিরাগ’ বা ‘বিতৃষ্ণা’।',
        status: 'published',
        subject: 'বাংলা ভাষা ও ব্যাকরণ',
        topic: 'শব্দ ও পদ',
        subtopic: 'বিপরীতার্থক শব্দ',
        code: 'BNG-LNG-01-04',
      },
      {
        id: 'Q-BNG-LNG-01-04-00003',
        question: '‘জঙ্গম’ শব্দের বিপরীতার্থক শব্দ কোনটি?',
        option_a: 'স্থাবর',
        option_b: 'ক্ষণস্থায়ী',
        option_c: 'গতিশীল',
        option_d: 'চঞ্চল',
        correct_answer: 'option_a',
        explanation: '‘জঙ্গম’ অর্থ যা গতিশীল বা সচল। এর বিপরীত শব্দ ‘স্থাবর’ (যা এক স্থানে স্থির)।',
        status: 'published',
        subject: 'বাংলা ভাষা ও ব্যাকরণ',
        topic: 'শব্দ ও পদ',
        subtopic: 'বিপরীতার্থক শব্দ',
        code: 'BNG-LNG-01-04',
      },
      {
        id: 'Q-BNG-LNG-01-04-00004',
        question: '‘উদ্ধত’ শব্দের সঠিক বিপরীত শব্দ কোনটি?',
        option_a: 'বিনয়ী',
        option_b: 'অহংকারী',
        option_c: 'নম্র',
        option_d: 'ক ও গ উভয়ই',
        correct_answer: 'option_d',
        explanation: '‘উদ্ধত’ শব্দের বিপরীত শব্দ হলো ‘বিনয়ী’ বা ‘নম্র’ (বিনীত)।',
        status: 'published',
        subject: 'বাংলা ভাষা ও ব্যাকরণ',
        topic: 'শব্দ ও পদ',
        subtopic: 'বিপরীতার্থক শব্দ',
        code: 'BNG-LNG-01-04',
      },
      {
        id: 'Q-BNG-LNG-01-04-00005',
        question: '‘প্রাচ্য’ শব্দের বিপরীত শব্দ কোনটি?',
        option_a: 'প্রতীচ্য',
        option_b: 'উদীচ্য',
        option_c: 'প্রাতঃ',
        option_d: 'প্রাচীর',
        correct_answer: 'option_a',
        explanation: '‘প্রাচ্য’ (পূর্বদেশীয়) শব্দের সঠিক বিপরীত শব্দ ‘প্রতীচ্য’ (পশ্চিমদেশীয়)।',
        status: 'published',
        subject: 'বাংলা ভাষা ও ব্যাকরণ',
        topic: 'শব্দ ও পদ',
        subtopic: 'বিপরীতার্থক শব্দ',
        code: 'BNG-LNG-01-04',
      },
    ],
  },
  {
    id: 'EX-ENG-002',
    title: 'English Grammar — Appropriate Preposition',
    badge: 'দৈনিক পরীক্ষা',
    badge_type: 'daily',
    subject: 'English Grammar',
    topic: 'Parts of Speech',
    post: 'বিসিএস ক্যাডার (BCS)',
    description: 'English Grammar Appropriate Preposition অনুশীলন প্রশ্নাবলী।',
    question_count: 4,
    time_minutes: 5,
    total_marks: 4,
    negative_marks: 0.25,
    marks_per_question: 1,
    has_negative_marking: true,
    pass_mark: 3,
    status: 'active',
    category: 'দৈনিক মডেল টেস্ট (Daily Test)',
    exam_type: 'course',
    exam_format: 'MCQ (বহুনির্বাচনি)',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    questions: [
      {
        id: 'Q-ENG-GRM-06-02-00001',
        question: 'Identify the correct preposition: He is senior _____ me.',
        option_a: 'than',
        option_b: 'to',
        option_c: 'from',
        option_d: 'with',
        correct_answer: 'option_b',
        explanation: 'Latin comparative adjectives like senior, junior, superior, inferior take the preposition "to".',
        status: 'published',
        subject: 'English Grammar',
        topic: 'Parts of Speech',
        subtopic: 'Preposition',
        code: 'ENG-GRM-06-02',
      },
      {
        id: 'Q-ENG-GRM-06-02-00002',
        question: 'Choose the appropriate preposition: He is good ___ Mathematics.',
        option_a: 'in',
        option_b: 'at',
        option_c: 'on',
        option_d: 'for',
        correct_answer: 'option_b',
        explanation: 'The phrase "good at" means skillful or capable in a subject or activity.',
        status: 'published',
        subject: 'English Grammar',
        topic: 'Parts of Speech',
        subtopic: 'Preposition',
        code: 'ENG-GRM-06-02',
      },
      {
        id: 'Q-ENG-GRM-06-02-00003',
        question: 'Which preposition correctly completes the sentence: "She preferred tea ___ coffee"?',
        option_a: 'than',
        option_b: 'over',
        option_c: 'to',
        option_d: 'against',
        correct_answer: 'option_c',
        explanation: 'The verb "prefer" is followed by the preposition "to" when comparing two choices.',
        status: 'published',
        subject: 'English Grammar',
        topic: 'Parts of Speech',
        subtopic: 'Preposition',
        code: 'ENG-GRM-06-02',
      },
      {
        id: 'Q-ENG-GRM-06-02-00004',
        question: 'Select the appropriate preposition: "He died ___ overeating."',
        option_a: 'of',
        option_b: 'from',
        option_c: 'by',
        option_d: 'for',
        correct_answer: 'option_b',
        explanation: 'One dies "of" a disease, but dies "from" an external cause or overeating/wound.',
        status: 'published',
        subject: 'English Grammar',
        topic: 'Parts of Speech',
        subtopic: 'Preposition',
        code: 'ENG-GRM-06-02',
      },
    ],
  },
];

