import { Exam, Question } from '../types';

export const INITIAL_SEED_EXAMS: Exam[] = [
  {
    id: 'EX-BANGLA-001',
    title: 'বাংলা — BCS',
    badge: 'ফ্রি পরীক্ষা',
    badge_type: 'free',
    subject: 'বাংলা',
    topic: 'ভাষা আন্দোলন ও মুক্তিযুদ্ধ',
    post: 'বিসিএস ক্যাডার (BCS)',
    description: 'বাংলাদেশের জাতীয় ফুল, ভাষা আন্দোলন ও মুক্তিযুদ্ধ বিষয়ক ৫টি MCQ প্রশ্ন।',
    question_count: 5,
    time_minutes: 2,
    total_marks: 5,
    negative_marks: 0.25,
    marks_per_question: 1,
    has_negative_marking: true,
    pass_mark: 3,
    status: 'active',
    category: 'ফ্রি ট্রায়াল টেস্ট (Free Test)',
    exam_type: 'free',
    exam_format: 'MCQ (বহুনির্বাচনি)',
    created_at: new Date().toISOString(),
    questions: [
      {
        id: 'Q-BANGLA-001',
        question: 'বাংলাদেশের জাতীয় ফুল কোনটি?',
        option_a: 'গোলাপ',
        option_b: 'শাপলা',
        option_c: 'বেলি',
        option_d: 'জবা',
        correct_answer: 'option_b',
        explanation: 'বাংলাদেশের জাতীয় ফুল সাদা শাপলা (Nymphaea nouchali)।',
        status: 'published',
        subject: 'বাংলা',
      },
      {
        id: 'Q-BANGLA-002',
        question: 'ভাষা আন্দোলনের শহীদ বরকত কোন বিশ্ববিদ্যালয়ের ছাত্র ছিলেন?',
        option_a: 'ঢাকা বিশ্ববিদ্যালয়',
        option_b: 'রাজশাহী বিশ্ববিদ্যালয়',
        option_c: 'চট্টগ্রাম বিশ্ববিদ্যালয়',
        option_d: 'বুয়েট',
        correct_answer: 'option_a',
        explanation: 'শহীদ আবুল বরকত ঢাকা বিশ্ববিদ্যালয়ের রাষ্ট্রবিজ্ঞান বিভাগের এম.এ শেষ বর্ষের ছাত্র ছিলেন।',
        status: 'published',
        subject: 'বাংলা',
      },
      {
        id: 'Q-BANGLA-003',
        question: '‘আমার ভাইয়ের রক্তে রাঙানো একুশে ফেব্রুয়ারি’ গানটির রচয়িতা কে?',
        option_a: 'আলতাফ মাহমুদ',
        option_b: 'আবদুল গাফফার চৌধুরী',
        option_c: 'শামসুর রাহমান',
        option_d: 'কাজী নজরুল ইসলাম',
        correct_answer: 'option_b',
        explanation: 'গানটির গীতিকার আবদুল গাফফার চৌধুরী এবং বর্তমান সুরকার আলতাফ মাহমুদ।',
        status: 'published',
        subject: 'বাংলা',
      },
      {
        id: 'Q-BANGLA-004',
        question: 'মুক্তিযুদ্ধকালে বাংলাদেশকে কয়টি সেক্টরে বিভক্ত করা হয়েছিল?',
        option_a: '৯টি',
        option_b: '১১টি',
        option_c: '৬৪টি',
        option_d: '৭টি',
        correct_answer: 'option_b',
        explanation: '১৯৭১ সালের মহান মুক্তিযুদ্ধে বাংলাদেশকে মোট ১১টি প্রশাসনিক সেক্টরে ভাগ করা হয়।',
        status: 'published',
        subject: 'বাংলা',
      },
      {
        id: 'Q-BANGLA-005',
        question: '‘একাত্তরের দিনগুলি’ কার রচিত স্মৃতিচারণমূলক গ্রন্থ?',
        option_a: 'জাহানারা ইমাম',
        option_b: 'সুফিয়া কামাল',
        option_c: 'সেলিনা হোসেন',
        option_d: 'বেগম রোকেয়া',
        correct_answer: 'option_a',
        explanation: 'শহীদ জননী জাহানারা ইমামের মুক্তিযুদ্ধ ভিত্তিক দিনলিপি ‘একাত্তরের দিনগুলি’।',
        status: 'published',
        subject: 'বাংলা',
      },
    ],
  },
  {
    id: 'EX-ENG-002',
    title: 'ইংরেজি — BCS',
    badge: 'ড্রাফট',
    badge_type: 'daily',
    subject: 'English',
    topic: 'Grammar, Vocabulary এবং Sentence Completion',
    post: 'বিসিএস ক্যাডার (BCS)',
    description: 'Grammar, Vocabulary এবং Sentence Completion নিয়ে ১০টি প্রশ্ন।',
    question_count: 10,
    time_minutes: 15,
    total_marks: 10,
    negative_marks: 0.25,
    marks_per_question: 1,
    has_negative_marking: true,
    pass_mark: 6,
    status: 'draft',
    category: 'দৈনিক মডেল টেস্ট (Daily Test)',
    exam_type: 'course',
    exam_format: 'MCQ (বহুনির্বাচনি)',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    questions: [
      {
        id: 'Q-ENG-001',
        question: 'What is the synonym of the word "Candid"?',
        option_a: 'Frank',
        option_b: 'Dishonest',
        option_c: 'Secretive',
        option_d: 'Arrogant',
        correct_answer: 'option_a',
        explanation: 'Candid means truthful and straightforward; frank.',
        status: 'published',
        subject: 'English',
      },
      {
        id: 'Q-ENG-002',
        question: 'Identify the correct sentence:',
        option_a: 'He is senior than me.',
        option_b: 'He is senior to me.',
        option_c: 'He is more senior than me.',
        option_d: 'He is senior from me.',
        correct_answer: 'option_b',
        explanation: 'Latin comparatives like senior, junior, superior take preposition "to".',
        status: 'published',
        subject: 'English',
      },
      {
        id: 'Q-ENG-003',
        question: 'Choose the correctly spelled word:',
        option_a: 'Bureaucracy',
        option_b: 'Beurocracy',
        option_c: 'Bureaucrasy',
        option_d: 'Burocracy',
        correct_answer: 'option_a',
        explanation: 'Correct spelling is Bureaucracy.',
        status: 'published',
        subject: 'English',
      },
      {
        id: 'Q-ENG-004',
        question: 'The idiom "A white elephant" means:',
        option_a: 'A rare animal',
        option_b: 'A very costly and useless possession',
        option_c: 'An auspicious sign',
        option_d: 'A powerful person',
        correct_answer: 'option_b',
        explanation: 'A white elephant refers to a burdensome possession.',
        status: 'published',
        subject: 'English',
      },
      {
        id: 'Q-ENG-005',
        question: 'Neither the teacher nor the students _____ present.',
        option_a: 'was',
        option_b: 'were',
        option_c: 'is',
        option_d: 'has been',
        correct_answer: 'option_b',
        explanation: 'With "neither...nor", the verb agrees with the closer subject ("students" - plural -> "were").',
        status: 'published',
        subject: 'English',
      },
      {
        id: 'Q-ENG-006',
        question: 'What is the antonym of "Meticulous"?',
        option_a: 'Careless',
        option_b: 'Precise',
        option_c: 'Painstaking',
        option_d: 'Diligent',
        correct_answer: 'option_a',
        explanation: 'Meticulous means showing great attention to detail; antonym is careless.',
        status: 'published',
        subject: 'English',
      },
    ],
  },
  {
    id: 'EX-GK-003',
    title: 'সাধারণ জ্ঞান — BCS',
    badge: 'মডেল টেস্ট',
    badge_type: 'weekly',
    subject: 'সাধারণ জ্ঞান',
    topic: 'বাংলাদেশ ও আন্তর্জাতিক বিষয়াবলী',
    post: 'বিসিএস ক্যাডার (BCS)',
    description: 'বাংলাদেশ ও আন্তর্জাতিক বিষয়ক ২৫টি গুরুত্বপূর্ণ প্রশ্ন।',
    question_count: 25,
    time_minutes: 25,
    total_marks: 25,
    negative_marks: 0.25,
    marks_per_question: 1,
    has_negative_marking: true,
    pass_mark: 15,
    status: 'active',
    category: 'সাপ্তাহিক মেগা টেস্ট (Weekly Mega)',
    exam_type: 'free',
    exam_format: 'MCQ (বহুনির্বাচনি)',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    questions: Array.from({ length: 25 }).map((_, idx) => ({
      id: `Q-GK-${String(idx + 1).padStart(3, '0')}`,
      question: `সাধারণ জ্ঞান টেস্ট প্রশ্ন #${idx + 1}: বাংলাদেশ ও বিশ্ব প্রেক্ষাপট`,
      option_a: 'অপশন ক',
      option_b: 'অপশন খ',
      option_c: 'অপশন গ',
      option_d: 'অপশন ঘ',
      correct_answer: 'option_a',
      explanation: 'ব্যাখ্যা: বাংলাদেশ সংবিধান ও ভৌগোলিক অবস্থানের বিস্তারিত তথ্য।',
      status: 'published',
      subject: 'সাধারণ জ্ঞান',
    })),
  },
  {
    id: 'EX-MATH-004',
    title: 'গণিত — প্রাথমিক শিক্ষক নিয়োগ',
    badge: 'লাইভ পরীক্ষা',
    badge_type: 'live',
    subject: 'গণিত',
    topic: 'মৌলিক ধারণা ও সমস্যা সমাধান',
    post: 'সহকারী শিক্ষক (প্রাইমারি)',
    description: 'গণিতের মৌলিক ধারণা ও সমস্যা সমাধান নিয়ে ২০টি প্রশ্ন।',
    question_count: 20,
    time_minutes: 20,
    total_marks: 20,
    negative_marks: 0.25,
    marks_per_question: 1,
    has_negative_marking: true,
    pass_mark: 12,
    status: 'active',
    category: 'লাইভ পরীক্ষা (Live Exam)',
    exam_type: 'free',
    exam_format: 'MCQ (বহুনির্বাচনি)',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    questions: Array.from({ length: 20 }).map((_, idx) => ({
      id: `Q-MATH-${String(idx + 1).padStart(3, '0')}`,
      question: `গণিত টেস্ট প্রশ্ন #${idx + 1}: শতকরা ও অনুপাতের নিয়মাবলী`,
      option_a: '১০%',
      option_b: '২০%',
      option_c: '২৫%',
      option_d: '৩০%',
      correct_answer: 'option_b',
      explanation: 'সমাধান: অনুপাত ও ঐকিক নিয়মের সূত্রানুসারে ফলাফল ২০%।',
      status: 'published',
      subject: 'গণিত',
    })),
  },
  {
    id: 'EX-MOCK-01',
    title: 'BCS Preliminary Mock Test 01',
    badge: 'Scheduled',
    badge_type: 'weekly',
    subject: 'সকল বিষয়',
    topic: 'পূর্ণাঙ্গ মক টেস্ট',
    post: 'বিসিএস ক্যাডার (BCS)',
    description: 'পূর্ণাঙ্গ মক টেস্ট — ২০০ প্রশ্ন\nবাংলা, ইংরেজি, গণিত, সাধারণ জ্ঞান',
    question_count: 200,
    time_minutes: 180,
    total_marks: 200,
    negative_marks: 0.25,
    marks_per_question: 1,
    has_negative_marking: true,
    pass_mark: 120,
    status: 'upcoming',
    category: 'সাপ্তাহিক মেগা টেস্ট (Weekly Mega)',
    exam_type: 'course',
    exam_format: 'MCQ (বহুনির্বাচনি)',
    created_at: new Date(Date.now() + 5 * 86400000).toISOString(),
    start_date: new Date(Date.now() + 5 * 86400000).toISOString(),
    questions: Array.from({ length: 200 }).map((_, idx) => ({
      id: `Q-MOCK-${String(idx + 1).padStart(4, '0')}`,
      question: `বিসিএস পূর্ণাঙ্গ মক প্রশ্ন #${idx + 1}`,
      option_a: 'অপশন ক',
      option_b: 'অপশন খ',
      option_c: 'অপশন গ',
      option_d: 'অপশন ঘ',
      correct_answer: 'option_a',
      status: 'published',
      subject: 'সকল বিষয়',
    })),
  },
];
